### PR TITLE
Updates for initscripts

### PR DESCRIPTION
**Pull request by protonesso**
Add new initscripts with udev support

### CODE REVIEW

**Comment by tpimh** [comment]
Looks promising, I will test it next week.

**Comment by tpimh** [comment]
I think base-files will probably need to be moved to own repo. Maybe I will create github organization for all related repos before releasing v0.1.

**Comment by protonesso** [comment]
Does init work

**Comment by tpimh** [comment]
I need to test with a real kernel, but probably shouldn't be any problems with it. I would prefer replacing tabs with spaces, but other than this, LGTM.

**Comment by tpimh** [comment]
Just tested with a real kernel, had to enable init and getty in toybox as they are not enabled by default. There are problems with shadow, but they should be easy to fix: force passwd to `/bin/passwd` and change `/etc/shadow` contents to `root::1:0:99999:7:0::` (for some reason it doesn't like passwords set on Jan 1 1970).
There are also some problems with init scripts:
- `/bin/rc.boot: Syntax error: "fi" unexpected (expecting "then")` (actually just missing "n", easy fix)
- `sysctl -p` doesn't seem to be called on boot
- `$(cat /etc/hostname)` actually gets executed on build machine, not on the target system
- `fsck` searches for fstab that doesn't exist
- `swapon` from toybox doesn't support `-a` option (and also tries to access fstab)

I only tested with toybox init now, maybe there will be more problems with procd.

**Comment by protonesso** [comment]
use swapon from util-linux
sysctl from procps-ng

**Comment by tpimh** [comment]
base-files package now moved to a separate repo: https://github.com/tpimh/nenuzhnix/commit/2da3fc1bf2155e04644e5eacbe367a864b514b94
Please propose the changes [here](https://github.com/tpimh/nenuzhnix-base-files).
This pull-request can be closed.

**Pull request closed without merging**
